### ISSUE TITLE
Setup: Overview

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#1]
- [x] GitHub
  - [x] What is GitHub?
  - [x] What is a repository?
- [x] Terminal
  - [x] What is a terminal?
  - [x] What is the home folder?
  - [x] What is an alias?
- [x] Visual Studio Code
  - [x] What is Visual Studio Code?
  - [x] How can I customize Visual Studio Code?
- [x] Markdown
  - [x] What is Markdown?
  - [x] How can I structure documents with Markdown?

**Comment by SzabiSch** [comment]
I think its time for the next Step
