### ISSUE TITLE
Git Intro: Visual Studio Code and Git

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#27]
Get familiar with the Git integration in Visual Studio Code. 

- [x] Read [this article](https://www.digitalocean.com/community/tutorials/how-to-use-git-integration-in-visual-studio-code-de) about Git Integration in VS Code
- [x] Install the [Git Graph Extension](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) in VS Code

**Comment by SzabiSch** [comment]
gelesen ja, verstanden ja, Verwendung in der Praxis? es stellt noch heraus
