### ISSUE TITLE
Git Intro: Push to GitHub

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#28]
- [x] Go to GitHub and login with your GitHub Account
- [x] Create a new repository `git-test` on GitHub
- [x] Add your GitHub repository as a new remote to your local repository
- [x] Push your current branch to GitHub

**Comment by SzabiSch** [comment]
es sind noch offene Fragen, wie z.B.: ohne ssh key, ist möglich, wenn ja wie? 
Andere Account, anderes Laptop -> Fehlermeldung ???
