### ISSUE TITLE
Git Intro: Clone existing CV repository from GitHub

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#29]
You will now remove your local CV folder to clone it again from GitHub. 

> While this sound a little strange it's the easiest way to connect your local CV folder to GitHub

- [x] Add all your local changes to your CV repository on GitHub 
- [x] Remove your local cv folder
- [x] Go to your cv repository on GitHub
- [x] Copy the clone link 
  - Use HTTPS if you haven't configured SSH yet - otherwise use SSH 💡
- [x] Clone the repository onto your computer (into your coding folder)
 
> 🚨 Heads up where you use the `git clone` command because it will create a new folder including a git repository

**Comment by SzabiSch** [comment]
war leichter als gedacht, aber im Praxis bzw als Routin, wir werden sehen
