### ISSUE TITLE
Kata: Password Check

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#81]
You will build a password check app.

## Styling

- [x] Style the app as visible on the screenshots and in the video
- [x] Use `lightsalmon` as background color
- [x] Use [Lobster](https://fonts.google.com/specimen/Lobster) for Headings and [Open Sans](https://fonts.google.com/specimen/Open+Sans) for all other text
- [x] Use Open Sans also for inputs and buttons
- [x] Use a one column layout below 700px screen width
- [x] Use a two column layout above 700px screen width
- [x] Use emojis (either from your emoji keyboard or [emojicopy](https://www.emojicopy.com/)) for valid or invalid checks
- [x] Inputs and buttons should have
  - [x] A black border
  - [x] A 2px border radius 

## Features

- [x] Add these five checks
  - [x] Passwords are equal
  - [x] Password contains at least one lower case character
  - [x] Password contains at least one upper case character
  - [x] Password contains at least one number
  - [x] Passwort is at least 10 characters long
- [x] The first check is always the "equality check" of both passwords
  - [x] If this first check fails all other checks will be failed automatically
- [x] Run all checks whenever the user types into any of the password inputs 
- [x] Add a button that toggles the text in the password fields and the label of the button itself
  - [x] If the passwords are hidden the text of the button is "Show Passwords"
  - [x] If the passwords are visible the text of the button is "Hide Passwords"

## Development Process

- [x] Create a new repository locally and on GitHub
- [x] Make an initial commit with a `README.md` on the main branch
- [x] Make all other commits on a new branch called `password-check`
- [x] Use meaningful commit messages
- [x] Push all your code to GitHub
- [x] Create a new pull request at the end of the day that will merge your `password-check` branch into the `main` branch
- [x] Do not merge the branch yourself
- [x] Assign the `codingbootcampseu` GitHub user `read` permission to your repo
- [x] Assign the `codingbootcampseu` user as reviewer to your pull request

## Screenshot Mobile

![image](https://user-images.githubusercontent.com/16404104/136382249-7c6860ea-1681-4a10-9732-fe5820881665.png)

## Screenshot Desktop

![image](https://user-images.githubusercontent.com/16404104/136382199-23e85f6f-1191-4329-abea-c215202d62c6.png)

## Video

https://user-images.githubusercontent.com/16404104/136382623-2a963825-f5db-49ac-9368-0cbce56e66cb.mov

**Comment by SzabiSch** [comment]
Es ist extrem mieeeeeees

**Comment by SzabiSch** [comment]
Problem gelöst, Ch. Lux hat mich über Ziellinie geschupst, aber nur Unaufmerksamkeit dank der vorherigen Denkweise!
trotzdem lustig
