### ISSUE TITLE
Setup: Node.js (Windows only)

### ISSUE THREAD

**Issue by codingbootcampseu** [SzabiSch/bootcamp-schedule#84]
You will now install Node.js.

- [x] Go to the [Node.js downloads page](https://nodejs.org/en/download/)
- [x] Dowload Node.js
- [x] Install it on your machine
- [x] Close all running terminals or shells
- [x] Open a new terminal and type the command `node --version` to check if node is correctly installed (you should see a version number)

**Comment by SzabiSch** [comment]
say NO to windows 🤣
